### ISSUE TITLE
Koa v2 support

### ISSUE THREAD

**Issue by noraesae** [yosuke-furukawa/koa-livereload#6]
Hello,

As you may already know, the Koa middleware framework will be changed in v2 as described in the following documentation.

- https://github.com/koajs/koa/tree/v2.x#middleware

The old middlewares can also be used with [koa-convert](https://github.com/koajs/convert), but it may be good idea to get prepared for the next version.

Other middlewares are also providing their new version with `next` branch and release. (e.g. [koa-static@next](https://github.com/koajs/static/tree/next))

If you don't mind, I will do some work for this. Please let me know if there's any comment.

Thanks,

**Comment by noraesae** [comment]
PR uploaded.

**Comment by yosuke-furukawa** [comment]
Thank you!! landed in v0.2.0 !!

**Comment by noraesae** [comment]
You're welcome 😄
